### ISSUE TITLE
KeyError when do prediction in chinese 

### ISSUE THREAD

**Issue by smartcatdog** [cdathuraliya/bert-inference#1]
Hello,
when i use bert-inference to predict the classification of a sentence, the key error is appeared named 
"""
Traceback (most recent call last):
  File "bert-inference.py", line 8, in <module>
    result = predictor.run("科技感十足.")
  File "bert/prediction.py", line 75, in run
    self.__class__.tokenizer)
  File "bert/prediction.py", line 60, in convert_line
    feature = rc.convert_single_example(0, example, label_list, max_seq_length, tokenizer)
  File "bert/run_classifier.py", line 494, in convert_single_example
    label_id = label_map[example.label]
KeyError: u'0'  
"""
what is the problem, thank you for help

**Comment by cdathuraliya** [comment]
Hi @smartcatdog,
This can be due to non-ASCII characters. Can you please try the same with some other input in ASCII characters and see whether the problem persists?

**Comment by smartcatdog** [comment]
@cdathuraliya 
thanks,  it's ok now  because of two reasons:
Firstly, Chinese string should add character 'u' at the begin of the string text because of  unicode or utf-8 string in python as you say. For example ,  '科技感十足' in python3 wile  u'科技感十足' in python2.
 I'm using python2 to run bert currently.
Secondly, prediction text should mock a label at the begin of the text storing to tsv keeping pace with the labels in trained data or modify the code in prediction.py 
from
"label = tokenization.convert_to_unicode("0") # Mock label"
to 
"label = tokenization.convert_to_unicode(<label in trained data>) # Mock label"
while <label in trained data> represents one label in trained data not 0/1 but chinese named "科技" and etc
